### ISSUE TITLE
JavaScript Data Types Quiz

### ISSUE THREAD

**Issue by mmmz21** [learn-co-curriculum/javascript-data-types-quiz#10]
For question 2, -'4' should not be marked as a correct answer to the question "Which of the following is/are numbers?" because it is not a number, it is a string.

**Comment by mendelB** [comment]
@Shagalabagalados Interestingly enough, `-'4'` would indeed return a number. I assume this happens due to the `-` operation telling Javascript that we'd like to operate on `'4'` as a number and not a string.
