### ISSUE TITLE
Solutions already displayed

### ISSUE THREAD

**Issue by Hector-Ariceaga** [learn-co-curriculum/javascript-data-types-quiz#12]
The first 3 questions allow you to select an answer and then the last several questions automatically display the correct answer. This is true even upon refreshing the page.

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If Learn is misbehaving, please direct your bug report to bugs@learn.co.

As always, thanks for contributing! 💙
