### ISSUE TITLE
What's the value in knowing the typeof null and NaN this early in the curriculum?

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/javascript-data-types-quiz#2]
They have only written one line of code and we are testing them on some advanced JS typeof trivia. Seems a bit too difficult too fast?

Also in general, when has knowing the typeof those things helped out for this early in your JS career?

**Comment by pletcher** [comment]
Agreed, removing that stuff and giving them more practice with strings v. numbers :)
