### ISSUE TITLE
Having multiple correct answers and only being able to select 1 could be confusing

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/javascript-data-types-quiz#4]
The question "Which of the following is/are numbers?" has multiple correct options, but there is no way to select more than one answer. This seems a little confusing. Can we either only have one correct answer, or change the format so students must select all correct answers? 
@pletcher

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by devinburnette** [comment]
Yea i noticed the same thing, it almost seems like the formatting for all the questions after the first are off. That same question it marked 4.0 as a wrong answer, so def. should fix that one as typeof 4.0 returns number. @aturkewi @pletcher

**Comment by pletcher** [comment]
Probably all of the quizzes are off -- it's a syntax issue. I'll fix them.

**Comment by pletcher** [comment]
Fixed :)
