### ISSUE TITLE
Need to mark Quiz as completed twice

### ISSUE THREAD

**Issue by abhishekpillai** [learn-co-curriculum/javascript-data-types-quiz#9]
**For this quiz, it starts like this:**
<img width="291" alt="screen shot 2016-07-06 at 11 06 57 pm" src="https://cloud.githubusercontent.com/assets/1326555/16641455/b085553e-43ce-11e6-8639-cf8cf10c6029.png">

**When I finish the quiz:**
<img width="327" alt="screen shot 2016-07-06 at 11 08 08 pm" src="https://cloud.githubusercontent.com/assets/1326555/16641456/b1f86a14-43ce-11e6-87d2-9d19165cb4dd.png">

**After that, I have to mark it done as well**
<img width="309" alt="screen shot 2016-07-06 at 11 08 22 pm" src="https://cloud.githubusercontent.com/assets/1326555/16641458/b3819e78-43ce-11e6-9cc6-cf2bc3563fe8.png">

This is a Learn "issue" - I wonder if this is expected @spencer1248

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by pletcher** [comment]
@spencer1248 is this expected behavior?

**Comment by pletcher** [comment]
@spencer1248 is this expected behavior?

**Comment by spencerarogers** [comment]
No, I don't believe so. It obviously doesn't make a ton of sense whether it's expected or not, I'll open an issue on Learn.

**Comment by pletcher** [comment]
Thanks!
